# SIB - Exercícios de Avaliação 
### Karolina Lopes Barbosa - PG55129

In [12]:
import pandas as pd 
import numpy as np
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.tanimoto_similarity import tanimoto_similarity
from si.decomposition.pca import PCA
from si.model_selection.split import stratified_train_test_split, train_test_split
from si.models.knn_regressor import KNNRegressor
from si.models.random_forest_classifier import RandomForestClassifier
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.model_selection.cross_validate import k_fold_cross_validation
from si.neural_networks.layers import Dropout
from si.neural_networks.activation import TanhActivation, SoftmaxActivation
from si.neural_networks.activation import SigmoidActivation, ReLUActivation
from si.neural_networks.losses import CategoricalCrossEntropy

### Exercise 1: NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [13]:
df = pd.read_csv('../datasets/iris/iris.csv')
#print(iris_dataset.to_string())
#iris_np = iris_dataset.to_numpy() 

print(df)
X = df.iloc[:, :-1].to_numpy() #pega todas as linhas menos a ultima coluna
y = df.iloc[:, -1].to_numpy() #pega todas as linhas e a ultima coluna 
features = df.columns[:-1].tolist() 
label = df.columns[-1]

iris_dataset = Dataset(X, y, features, label)


     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [14]:
iris_dataset.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [15]:
#array[linhas, colunas]
iris_np = df.to_numpy()

ind_var_2 = iris_np[:,[2]]
dim = ind_var_2.shape #or ndim

print(ind_var_2) 
print(dim) #print dimension

[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]
 [1.7]
 [1.4]
 [1.5]
 [1.4]
 [1.5]
 [1.5]
 [1.6]
 [1.4]
 [1.1]
 [1.2]
 [1.5]
 [1.3]
 [1.4]
 [1.7]
 [1.5]
 [1.7]
 [1.5]
 [1.0]
 [1.7]
 [1.9]
 [1.6]
 [1.6]
 [1.5]
 [1.4]
 [1.6]
 [1.6]
 [1.5]
 [1.5]
 [1.4]
 [1.5]
 [1.2]
 [1.3]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.6]
 [1.9]
 [1.4]
 [1.6]
 [1.4]
 [1.5]
 [1.4]
 [4.7]
 [4.5]
 [4.9]
 [4.0]
 [4.6]
 [4.5]
 [4.7]
 [3.3]
 [4.6]
 [3.9]
 [3.5]
 [4.2]
 [4.0]
 [4.7]
 [3.6]
 [4.4]
 [4.5]
 [4.1]
 [4.5]
 [3.9]
 [4.8]
 [4.0]
 [4.9]
 [4.7]
 [4.3]
 [4.4]
 [4.8]
 [5.0]
 [4.5]
 [3.5]
 [3.8]
 [3.7]
 [3.9]
 [5.1]
 [4.5]
 [4.5]
 [4.7]
 [4.4]
 [4.1]
 [4.0]
 [4.4]
 [4.6]
 [4.0]
 [3.3]
 [4.2]
 [4.2]
 [4.2]
 [4.3]
 [3.0]
 [4.1]
 [6.0]
 [5.1]
 [5.9]
 [5.6]
 [5.8]
 [6.6]
 [4.5]
 [6.3]
 [5.8]
 [6.1]
 [5.1]
 [5.3]
 [5.5]
 [5.0]
 [5.1]
 [5.3]
 [5.5]
 [6.7]
 [6.9]
 [5.0]
 [5.7]
 [4.9]
 [6.7]
 [4.9]
 [5.7]
 [6.0]
 [4.8]
 [4.9]
 [5.6]
 [5.8]
 [6.1]
 [6.4]
 [5.6]
 [5.1]
 [5.6]
 [6.1]
 [5.6]
 [5.5]
 [4.8]
 [5.4]
 [5.6]
 [5.1]
 [5.1]

1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [16]:
last_10 = iris_np[-10:,] 
#last_10 = iris_np[-10:,[3]]
#mean_last_10 = np.mean(last_10)

print(last_10)

[[6.7 3.1 5.6 2.4 'Iris-virginica']
 [6.9 3.1 5.1 2.3 'Iris-virginica']
 [5.8 2.7 5.1 1.9 'Iris-virginica']
 [6.8 3.2 5.9 2.3 'Iris-virginica']
 [6.7 3.3 5.7 2.5 'Iris-virginica']
 [6.7 3.0 5.2 2.3 'Iris-virginica']
 [6.3 2.5 5.0 1.9 'Iris-virginica']
 [6.5 3.0 5.2 2.0 'Iris-virginica']
 [6.2 3.4 5.4 2.3 'Iris-virginica']
 [5.9 3.0 5.1 1.8 'Iris-virginica']]


1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [17]:
values = iris_np[:,0:3] <= 6
count_values = np.sum(values)
print(count_values)



380


1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain?

In [18]:
no_setosa = iris_np[:,-1] != 'Iris-setosa'

iris_filtered = iris_np[no_setosa]
print(iris_filtered)

[[7.0 3.2 4.7 1.4 'Iris-versicolor']
 [6.4 3.2 4.5 1.5 'Iris-versicolor']
 [6.9 3.1 4.9 1.5 'Iris-versicolor']
 [5.5 2.3 4.0 1.3 'Iris-versicolor']
 [6.5 2.8 4.6 1.5 'Iris-versicolor']
 [5.7 2.8 4.5 1.3 'Iris-versicolor']
 [6.3 3.3 4.7 1.6 'Iris-versicolor']
 [4.9 2.4 3.3 1.0 'Iris-versicolor']
 [6.6 2.9 4.6 1.3 'Iris-versicolor']
 [5.2 2.7 3.9 1.4 'Iris-versicolor']
 [5.0 2.0 3.5 1.0 'Iris-versicolor']
 [5.9 3.0 4.2 1.5 'Iris-versicolor']
 [6.0 2.2 4.0 1.0 'Iris-versicolor']
 [6.1 2.9 4.7 1.4 'Iris-versicolor']
 [5.6 2.9 3.6 1.3 'Iris-versicolor']
 [6.7 3.1 4.4 1.4 'Iris-versicolor']
 [5.6 3.0 4.5 1.5 'Iris-versicolor']
 [5.8 2.7 4.1 1.0 'Iris-versicolor']
 [6.2 2.2 4.5 1.5 'Iris-versicolor']
 [5.6 2.5 3.9 1.1 'Iris-versicolor']
 [5.9 3.2 4.8 1.8 'Iris-versicolor']
 [6.1 2.8 4.0 1.3 'Iris-versicolor']
 [6.3 2.5 4.9 1.5 'Iris-versicolor']
 [6.1 2.8 4.7 1.2 'Iris-versicolor']
 [6.4 2.9 4.3 1.3 'Iris-versicolor']
 [6.6 3.0 4.4 1.4 'Iris-versicolor']
 [6.8 2.8 4.8 1.4 'Iris-versicolor']
 

### Exercise 2: NumPy array Indexing/Slicing

2.1) Add a method to the Dataset class that removes
all samples containing at least one null value (NaN).
Note that the resulting object should not contain null
values in any independent feature/variable. Also,
note that you should update the y vector by
removing entries associated with the samples to be
removed. You should use only NumPy functions.
Method name: dropna

In [19]:
df_w_nas = pd.read_csv('../datasets/iris/iris_missing_data.csv', sep=',')

#definir X (var ind - todas as colunas menos a ultima)
X_w_nas = df_w_nas.iloc[:, :-1].to_numpy()

#fazer novo dataset com nas
dataset_w_nas = Dataset(X_w_nas, y, features, label)

#tirar nas do dataset
dataset_dropna = dataset_w_nas.dropna()

2.2) Add a method to the Dataset class that
replaces all null values with another value or the
mean or median of the feature/variable. Note that
the resulting object should not contain null values
in any independent feature/variable. You should
use only NumPy functions.
Method name: fillna

In [20]:
dataset_w_nas.X
fill_nas = dataset_w_nas.fillna("median")
#fill_nas = dataset_w_nas.fillna("mean")
#fill_nas = dataset_w_nas.fillna(0)
fill_nas.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 1.3],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 3. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 1.3],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

 2.3) Add a method to the Dataset class that
removes a sample by its index. Note that you
should also update the y vector by removing the
entry associated with the sample to be removed.
You should use only NumPy functions.
Method name: remove_by_index

In [21]:
remove_index = iris_dataset.remove_by_index([1,3])
remove_index.shape()

(148, 4)

### Exercise 3: Implementing SelectPercentile

3.1) Add the SelectPercentile object to the
feature_selection sub-package. You should create a
module called "select_percentile.py" to implement
this object. 

3.2) Test the SelectPercentile class in a Jupyter
notebook using the "iris.csv" dataset
(classification).

In [22]:
selector = SelectPercentile(percentile=40)
selector = selector.fit(iris_dataset)
print("\nOriginal example - F-scores:", selector.F)
print("Selected features (40%):", selector.transform(iris_dataset).features)
print("Number of features:", len(selector.transform(iris_dataset).features))


Original example - F-scores: [ 113.91732389   48.74222679 1134.44343705  923.18929086]
Selected features (40%): [np.str_('petal_length'), np.str_('petal_width')]
Number of features: 2


### Exercise 4: Implementing Tanimoto Similarity

4.1) Implement the Tanimoto Similarity in file tanimoto_similarity.py (in the sub-package statistics) in file tanimoto_similarity.py (in the sub-package statistics)

In [23]:
x = iris_dataset.X[0]      # Primeira amostra: shape (4,)
y = iris_dataset.X         # Todas as amostras: shape (148, 4)
print(f"x = {x}")
print(f"y shape = {y.shape}")
print(f"Similarities = {tanimoto_similarity(x, y)}")

x = [5.1 3.5 1.4 0.2]
y shape = (148, 4)
Similarities = [1.         0.99302762 0.9995015  0.99136952 0.99282869 0.99924185
 0.9760158  0.99423782 0.99672668 0.99639175 0.99061914 0.97169811
 0.98307292 0.97451431 0.99308596 0.9997518  0.98787478 0.9973545
 0.99548157 0.99781712 0.98892405 0.99453552 0.99112351 0.99222395
 0.9974887  0.99951136 0.99950544 0.99231585 0.99234828 0.99640891
 0.99100968 0.98568282 0.99423782 0.99636929 0.99598394 0.99423782
 0.97890295 0.99950087 0.99924357 0.94755043 0.98365198 0.99479167
 0.99104407 0.99062918 0.99688399 0.99081081 0.9978678  0.99872123
 0.77031093 0.7940806  0.75418202 0.81428294 0.77555798 0.79562172
 0.77923278 0.87417067 0.78225182 0.83336663 0.83723002 0.81780031
 0.81666667 0.7785148  0.86856128 0.79634788 0.79463975 0.83231538
 0.76380572 0.8380117  0.76510598 0.8317624  0.74573114 0.78105056
 0.80786961 0.79634876 0.75862069 0.74268171 0.79154129 0.87431804
 0.84097737 0.85141461 0.84221427 0.73533509 0.79317697 0.79856934
 0.7723

### Exercise 5: Implement the PCA Class

5.1) Add the "PCA" class in the "pca.py" module on
the "decomposition" sub-package. Consider the
PCA class structure presented in the next slide.

5.2) Test the PCA class in a jupyter notebook using
the iris.csv dataset (classificação).

In [24]:
pca_iris = PCA(n_components=4)
iris_X_reduced = pca_iris.fit_transform(iris_dataset)
print("Mean:")
print(pca_iris.mean)

print("\nComponents (eigenvectors):")
print(pca_iris.components)

print("\nExplained variance (ratio):")
print(pca_iris.explained_variance)

print("\nReduced dataset:")
print(iris_X_reduced)

Mean:
[5.85810811 3.05405405 3.78986486 1.21216216]

Components (eigenvectors):
[[ 0.36054742 -0.65788934 -0.5791591   0.31900144]
 [-0.08443357 -0.72898775  0.59616064 -0.32563834]
 [ 0.8568705   0.17377001  0.0716297  -0.48004804]
 [ 0.35867741  0.07458196  0.55139497  0.74950092]]

Explained variance (ratio):
[0.92316712 0.05403909 0.01751521 0.00527858]

Reduced dataset:
[[-2.72183113e+00 -3.17113775e-01 -2.43657900e-02  1.57878848e-03]
 [-2.92640707e+00  1.47361283e-01  2.12866862e-02  1.96745157e-02]
 [-2.76632922e+00 -3.24223616e-01  9.31661840e-02 -6.28851893e-02]
 [-2.31864370e+00 -7.39028279e-01  1.72118641e-01 -2.70903394e-02]
 [-2.85779374e+00  9.21878641e-02  2.60737191e-01 -5.04080070e-02]
 [-2.66375546e+00 -1.61049065e-01 -1.89029752e-02 -4.57623261e-02]
 [-2.92355417e+00  5.80801409e-01  2.33491917e-02 -2.63392204e-02]
 [-2.71034787e+00  1.15977997e-01 -1.94974756e-01 -5.49210623e-02]
 [-2.54486656e+00 -6.42901124e-01 -7.17184208e-02 -1.58532495e-02]
 [-2.65017789e+00 -

### Exercise 6: Implementing stratified splitting

6.1) In the "split.py" module of the
"model_selection" subpackage add
the "stratified_train_test_split" function.

6.2) Test the "stratified_train_test_split" function
with the iris dataset.

In [25]:
train_strat, test_strat = stratified_train_test_split(iris_dataset, test_size=0.2, random_state=42)

print(f"Train set: {len(train_strat.y)} samples")
unique, counts = np.unique(train_strat.y, return_counts=True)
for label, count in zip(unique, counts):
    print(f"  Class {label}: {count} samples ({count/len(train_strat.y)*100:.1f}%)")

print(f"\nTest set: {len(test_strat.y)} samples")
unique, counts = np.unique(test_strat.y, return_counts=True)
for label, count in zip(unique, counts):
    print(f"  Class {label}: {count} samples ({count/len(test_strat.y)*100:.1f}%)")
print()

Train set: 119 samples
  Class Iris-setosa: 39 samples (32.8%)
  Class Iris-versicolor: 40 samples (33.6%)
  Class Iris-virginica: 40 samples (33.6%)

Test set: 29 samples
  Class Iris-setosa: 9 samples (31.0%)
  Class Iris-versicolor: 10 samples (34.5%)
  Class Iris-virginica: 10 samples (34.5%)



### Exercise 7: Implementing the KNNRegressor with RMSE

7.1) Add the RMSE metric to the "metrics" sub-package.
You must create a new module named "rmse.py".
Consider the structure of the rmse function as presented
in the following slide.

In [26]:
from si.metrics.rmse import rmse
#o objetivo dos testes é verificar como se comportaria a função qnd n tem erros, com pequenos e maiores erros.
if __name__ == '__main__':
    print("=" * 70)
    print("TEST 1: Perfect predictions")
    print("=" * 70)
    y_true1 = np.array([1, 2, 3, 4, 5])
    y_pred1 = np.array([1, 2, 3, 4, 5])
    print(f"y_true: {y_true1}")
    print(f"y_pred: {y_pred1}")
    print(f"RMSE: {rmse(y_true1, y_pred1):.6f}")
    print("Expected: 0.0 (perfect predictions)")
    print()
    
    print("=" * 70)
    print("TEST 2: Small errors")
    print("=" * 70)
    y_true2 = np.array([3, -0.5, 2, 7])
    y_pred2 = np.array([2.5, 0.0, 2, 8])
    print(f"y_true: {y_true2}")
    print(f"y_pred: {y_pred2}")
    print(f"RMSE: {rmse(y_true2, y_pred2):.6f}")
    print("Errors: [-0.5, 0.5, 0, 1]")
    print()
    
    print("=" * 70)
    print("TEST 3: Larger errors")
    print("=" * 70)
    y_true3 = np.array([10, 20, 30, 40, 50])
    y_pred3 = np.array([12, 18, 35, 38, 55])
    print(f"y_true: {y_true3}")
    print(f"y_pred: {y_pred3}")
    print(f"RMSE: {rmse(y_true3, y_pred3):.6f}")
    print("Errors: [2, -2, 5, -2, 5]")
    print()
    
    print("=" * 70)
    print("TEST 5: Comparison - small vs large errors")
    print("=" * 70)
    y_true5 = np.array([10, 10, 10, 10])
    
    # Case A: consistent small errors
    y_pred5a = np.array([11, 11, 11, 11])
    rmse_a = rmse(y_true5, y_pred5a)
    print(f"Case A - Consistent small errors (+1 each):")
    print(f"  y_pred: {y_pred5a}")
    print(f"  RMSE: {rmse_a:.6f}")
    
    # Case B: one large error
    y_pred5b = np.array([10, 10, 10, 14])
    rmse_b = rmse(y_true5, y_pred5b)
    print(f"\nCase B - One large error (+4 on last):")
    print(f"  y_pred: {y_pred5b}")
    print(f"  RMSE: {rmse_b:.6f}")
    
    print(f"\nNote: RMSE penalizes large errors more heavily!")
    print(f"Case A (4 errors of +1): RMSE = {rmse_a:.3f}")
    print(f"Case B (1 error of +4): RMSE = {rmse_b:.3f}")
    print()
    
    print("=" * 70)
    print("TEST 6: Real-world example - House price prediction")
    print("=" * 70)
    # Prices in thousands of dollars
    y_true6 = np.array([250, 300, 350, 400, 450])  # True prices
    y_pred6 = np.array([245, 310, 340, 395, 460])  # Predicted prices
    
    print(f"True prices (K$): {y_true6}")
    print(f"Predicted prices (K$): {y_pred6}")
    print(f"RMSE: ${rmse(y_true6, y_pred6):.2f}K")
    print(f"\nInterpretation: On average, predictions are off by ~${rmse(y_true6, y_pred6):.2f}K")

TEST 1: Perfect predictions
y_true: [1 2 3 4 5]
y_pred: [1 2 3 4 5]
RMSE: 0.000000
Expected: 0.0 (perfect predictions)

TEST 2: Small errors
y_true: [ 3.  -0.5  2.   7. ]
y_pred: [2.5 0.  2.  8. ]
RMSE: 0.612372
Errors: [-0.5, 0.5, 0, 1]

TEST 3: Larger errors
y_true: [10 20 30 40 50]
y_pred: [12 18 35 38 55]
RMSE: 3.521363
Errors: [2, -2, 5, -2, 5]

TEST 5: Comparison - small vs large errors
Case A - Consistent small errors (+1 each):
  y_pred: [11 11 11 11]
  RMSE: 1.000000

Case B - One large error (+4 on last):
  y_pred: [10 10 10 14]
  RMSE: 2.000000

Note: RMSE penalizes large errors more heavily!
Case A (4 errors of +1): RMSE = 1.000
Case B (1 error of +4): RMSE = 2.000

TEST 6: Real-world example - House price prediction
True prices (K$): [250 300 350 400 450]
Predicted prices (K$): [245 310 340 395 460]
RMSE: $8.37K

Interpretation: On average, predictions are off by ~$8.37K


7.2) Add the "KNNRegressor" class to the "models" subpackage. You should create a module named
"knn_regressor.py" to implement this class. Consider the
structure of the "KNNRegressor" as presented in the next
slides.

7.3) Test the "KNNRegressor" class using the "cpu.csv"
dataset (regression).

In [27]:
df = pd.read_csv('../datasets/cpu/cpu.csv')

X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()
features = df.columns[:-1].tolist()
label = df.columns[-1]

cpu_dataset = Dataset(X, y, features, label)


 # Split the dataset
train_dataset, test_dataset = train_test_split(cpu_dataset, test_size=0.2, random_state=42)
print(f"Training samples: {train_dataset.shape()[0]}")
print(f"Testing samples: {test_dataset.shape()[0]}")

# Find best k value for KNN regressor 
k_values = [1, 3, 5, 10, 20]

print("Testing different k values:")
print("-" * 70)
for k in k_values:
    knn = KNNRegressor(k=k)
    knn.fit(train_dataset)
    score = knn.score(test_dataset)
    print(f"k={k:2d} -> RMSE: {score:.2f}")



Training samples: 168
Testing samples: 41
Testing different k values:
----------------------------------------------------------------------
k= 1 -> RMSE: 100.57
k= 3 -> RMSE: 81.36
k= 5 -> RMSE: 104.97
k=10 -> RMSE: 132.54
k=20 -> RMSE: 156.32


### Exercise 8: Implementing RidgeRegression with Least Squares


In the "models" sub-package add the
"ridge_regression_least_squares.py" module which will contain
the RidgeRegressionLeastSquates class 

In [28]:
from si.data.dataset import Dataset
from si.model_selection.split import train_test_split
from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares

# criar dataset aleatório
dataset = Dataset.from_random(n_samples=200, n_features=5)

# dividir entre treino e teste
train, test = train_test_split(dataset, test_size=0.2)

# criar modelo
model = RidgeRegressionLeastSquares(l2_penalty=1.0, scale=True)

# treinar
model.fit(train)

# mostrar parâmetros aprendidos
print("Theta (coeficientes):")
print(model.theta)

print("\nTheta_zero (intercepto):")
print(model.theta_zero)

# prever no test set
predictions = model.predict(test)

print("\nPrimeiras 10 previsões:")
print(predictions[:10])

print("\nPrimeiros 10 valores reais:")
print(test.y[:10])

# calcular score
score = model.score(test)
print(f"\nMSE score no test set: {score:.4f}")

Theta (coeficientes):
[ 0.04299948 -0.02005872  0.02527278  0.00540694 -0.00930056]

Theta_zero (intercepto):
0.5125000000000001

Primeiras 10 previsões:
[0.50072814 0.52228111 0.44321972 0.45068486 0.50499773 0.55127592
 0.5173332  0.54721859 0.49944067 0.51111671]

Primeiros 10 valores reais:
[0 0 0 0 0 0 0 0 1 1]

MSE score no test set: 0.2516


### Exercise 9: Implementing the RandomForestClassifier class

9.1) In the "models" sub-package add the
"random_forest_classifier.py" module. Implement the
RandomForestClassifier class by taking into consideration the
structure of the class shown in the next slides.

9.2) Test the random forest class using the following protocol:  


1.Use the iris.csv dataset. 

2.Split the data into train and test sets. 

3.Create the RandomForestClassifier model. 

4.Train the model. What is the score of the model on the test set?

In [29]:
if __name__ == "__main__":

    train, test = train_test_split(iris_dataset, test_size=0.2, random_state=42)

    model = RandomForestClassifier(
        n_estimators=10,
        max_depth=4,
        min_sample_split=2,
        mode="gini",
        seed=42
    )

    model.fit(train)
    preds = model.predict(test)
    print("Accuracy:", model.score(test))

Accuracy: 0.8620689655172413


### Exercise 10: Implementing the StackingClassifier ensemble

10.1) In the "ensemble" sub-package add the "stacking_classifier.py" module. Implement
the StackingClassifier class by taking into consideration the structure of the class shown
in the next slides.

In [30]:
import numpy as np
from si.base.model import Model
from si.data.dataset import Dataset
from si.metrics.accuracy import accuracy


class StackingClassifier(Model):
    """
    Stacking Classifier ensemble model.
    
    The StackingClassifier uses an ensemble of base models to generate predictions.
    These predictions are then used as features to train a final model that makes
    the ultimate predictions.
    
    Parameters
    ----------
    models : list
        List of base models to use in the ensemble
    final_model : Model
        The model to make the final predictions based on base model outputs
        
    Attributes
    ----------
    models : list
        The fitted base models
    final_model : Model
        The fitted final model
    """
    
    def __init__(self, models: list, final_model: Model, **kwargs):
        """
        Initialize the StackingClassifier.
        
        Parameters
        ----------
        models : list
            Initial set of base models
        final_model : Model
            The model to make the final predictions
        """
        super().__init__(**kwargs)
        self.models = models
        self.final_model = final_model
        
    def _fit(self, dataset: Dataset) -> 'StackingClassifier':
        """
        Train the stacking classifier.
        
        Algorithm:
        1. Train the initial set of models
        2. Get predictions from the initial set of models
        3. Train the final model with the predictions of the initial set of models
        4. Return itself (self)
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to fit the model to
            
        Returns
        -------
        self : StackingClassifier
            The fitted model
        """
        # Step 1: Train the initial set of models
        for model in self.models:
            model.fit(dataset)
        
        # Step 2: Get predictions from the initial set of models
        base_predictions = np.column_stack([
            model.predict(dataset) for model in self.models
        ])
        
        # Step 3: Train the final model with the predictions of the initial set of models
        # Create a new dataset with base predictions as features and original labels
        stacked_dataset = Dataset(X=base_predictions, y=dataset.y)
        self.final_model.fit(stacked_dataset)
        
        # Step 4: Return itself
        return self
    
    def _predict(self, dataset: Dataset) -> np.ndarray:
        """
        Predict class labels using the stacking classifier.
        
        Algorithm:
        1. Get predictions from the initial set of models
        2. Get the final predictions using the final model and the 
           predictions of the initial set of models
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to predict the classes of
            
        Returns
        -------
        predictions : np.ndarray
            Predicted class labels
        """
        # Step 1: Get predictions from the initial set of models
        base_predictions = np.column_stack([
            model.predict(dataset) for model in self.models
        ])
        
        # Step 2: Get the final predictions using the final model
        # Create a new dataset with base predictions as features
        stacked_dataset = Dataset(X=base_predictions, y=dataset.y)
        final_predictions = self.final_model.predict(stacked_dataset)
        
        return final_predictions
    
    def _score(self, dataset: Dataset, predictions: np.ndarray) -> float:
        """
        Compute the accuracy score of the stacking classifier.
        
        Algorithm:
        1. Compute the accuracy between predicted and real values
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to evaluate the model on
        predictions : np.ndarray
            An array with the predictions
            
        Returns
        -------
        accuracy : float
            The accuracy score (proportion of correct predictions)
        """
        # Compute the accuracy between predicted and real values
        return accuracy(dataset.y, predictions)


10.2) Test the StackingClassifier model using the following protocol:


1.Use the breast-bin.csv dataset


2.Split the data into train and test sets


3.Create a KNNClassifier model


4.Create a LogisticRegression model


5.Create a DecisionTree model


6.Create a second KNNClassifier model (final model)


7.Create a StackingClassifier model using the previous classifiers. The second KNNClassifier model must be used as the final model.


8.Train the StackingClassifier model. What is the score of the model on the test set?

In [31]:
df = pd.read_csv('../datasets/breast_bin/breast-bin.csv', header= None)
X = df.iloc[:, :-1].to_numpy()  # All columns except last
y = df.iloc[:, -1].to_numpy()    # Last column
features = [f'feature_{i}' for i in range(X.shape[1])]
label = 'target'


if __name__ == "__main__":
    
    bb_dataset = Dataset(X, y, features, label)

    # Initialize base models
    base_models = [
        KNNClassifier(k=3),
        LogisticRegression(),
        DecisionTreeClassifier()
    ]
    
    # Initialize final model
    final_model = KNNClassifier(k=3)
    
    # Create and train stacking classifier
    stacking = StackingClassifier(models=base_models, final_model=final_model)
    train_dataset, test_dataset = train_test_split(bb_dataset, test_size=0.2, random_state=42)
    stacking.fit(train_dataset)
    
    # Make predictions
    predictions = stacking.predict(test_dataset)
    print(f"Predictions: {predictions}")
    
    # Compute accuracy
    accuracy_score = stacking.score(test_dataset)
    print(f"Accuracy: {accuracy_score}")

Predictions: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1.]
Accuracy: 0.9280575539568345


### Exercise 11: Implementing the randomized_search_cv function.

11.1) In the "model_selection" sub-package add the "randomized_search.py"
module. Implement the randomized_search_cv function by considering the
structure presented in the next slides.

In [32]:
from typing import Dict, Callable, List, Any
import numpy as np
import itertools
from si.base.model import Model
from si.data.dataset import Dataset



def randomized_search_cv(model: Model,
                         dataset: Dataset,
                         hyperparameter_grid: Dict[str, List[Any]],
                         scoring: Callable = None,
                         cv: int = 3,
                         n_iter: int = 10,
                         seed: int = None) -> Dict[str, Any]:
    """
    Perform randomized search cross-validation on the given model and dataset.
    
    This function randomly samples n_iter combinations from the hyperparameter grid,
    evaluates each combination using k-fold cross-validation, and returns the best
    performing hyperparameters.

    Parameters
    ----------
    model : Model
        The model to validate
    dataset : Dataset
        The validation dataset
    hyperparameter_grid : Dict[str, List[Any]]
        Dictionary with the hyperparameter names as keys and lists of possible
        values to search as values
    scoring : Callable, optional
        Score function to use. If None, the model's score method will be used
    cv : int, default=3
        Number of cross-validation folds
    n_iter : int, default=10
        Number of random hyperparameter combinations to test
    seed : int, optional
        Random seed for reproducibility

    Returns
    -------
    results : Dict[str, Any]
        Dictionary with the following keys:
        - 'hyperparameters': list of all hyperparameter combinations tested
        - 'scores': list of mean scores obtained for each combination
        - 'best_hyperparameters': best combination of hyperparameters
        - 'best_score': best mean score achieved

    Raises
    ------
    ValueError
        If any hyperparameter in the grid does not exist in the model

    """

    # Step 1: Check if the provided hyperparameters are valid
    for hyperparameter in hyperparameter_grid.keys():
        if not hasattr(model, hyperparameter):
            raise ValueError(f"Model {model.__class__.__name__} does not have "
                           f"hyperparameter '{hyperparameter}'")
    
    # Step 2: Get n_iter hyperparameter combinations
    # Generate all possible combinations
    hyperparameter_names = list(hyperparameter_grid.keys())
    hyperparameter_values = list(hyperparameter_grid.values())
    all_combinations = list(itertools.product(*hyperparameter_values))
    
    # Randomly sample n_iter combinations (or all if n_iter > total combinations)
    if seed is not None:
        np.random.seed(seed)
    
    n_combinations = min(n_iter, len(all_combinations))
    random_indices = np.random.choice(len(all_combinations), 
                                     size=n_combinations, 
                                     replace=False)
    selected_combinations = [all_combinations[i] for i in random_indices]
    
    # Initialize results storage
    all_hyperparameters = []
    all_scores = []
    best_score = -np.inf
    best_hyperparameters = None
    
    # Step 3-6: Iterate through all selected hyperparameter combinations
    for combination in selected_combinations:
        # Step 3: Set the model hyperparameters with the current combination
        current_hyperparameters = {}
        for hyperparameter_name, hyperparameter_value in zip(hyperparameter_names, combination):
            setattr(model, hyperparameter_name, hyperparameter_value)
            current_hyperparameters[hyperparameter_name] = hyperparameter_value
        
        # Step 4: Cross validate the model using k_fold_cross_validation
        fold_scores = k_fold_cross_validation(model, dataset, scoring=scoring, cv=cv, seed=seed)
        
        # Step 5: Save the mean of the scores and respective hyperparameters
        mean_score = np.mean(fold_scores)
        all_hyperparameters.append(current_hyperparameters.copy())
        all_scores.append(mean_score)
        
        # Step 7: Update best score and hyperparameters if current is better
        if mean_score > best_score:
            best_score = mean_score
            best_hyperparameters = current_hyperparameters.copy()
    
    # Step 8: Return results dictionary
    results = {
        'hyperparameters': all_hyperparameters,
        'scores': all_scores,
        'best_hyperparameters': best_hyperparameters,
        'best_score': best_score
    }
    
    return results



11.2) Test the randomized_search_cv function using the following protocol:


1. Use the breast-bin.csv dataset


2. Create a LogisticRegression model


3. Perform a randomized search with the following hyperparameter distributions:


• l2_penalty: distribution between 1 and 10 with 10 equal intervals (e.g., np.linspace(1, 10, 10))

• alpha: distribution between 0.001 and 0.0001 with 100 equal intervals (e.g., np.linspace(0.001, 0.0001, 100))

• max_iter: distribution between 1000 and 2000 with 200 equal intervals (e.g., np.linspace(1000, 2000, 200))


4. Use n_iter=10 and cv=3 folds for the cross validation.


5. Which scores do you obtain? What are the best score and best hyperparameters?

In [33]:

if __name__ == "__main__":
    
    # Create model
    model = LogisticRegression()
    
    # Define hyperparameter grid with distributions for LogisticRegression
    hyperparameter_grid = {
        'l2_penalty': np.linspace(1, 10, 10).tolist(),
        'alpha': np.linspace(0.001, 0.0001, 100).tolist(),
        'max_iter': np.linspace(1000, 2000, 200, dtype=int).tolist()
    }
    
    # Perform randomized search
    print("Performing Randomized Search CV...")
    results = randomized_search_cv(
        model=model,
        dataset=dataset,
        hyperparameter_grid=hyperparameter_grid,
        cv=3,
        n_iter=10,  # Test 10 random combinations out of 200,000 possible
        seed=42
    )
    
    # Display results
    print("\nRandomized Search Results:")
    print("=" * 20)

    print(f"{'Score':<10}")

    print("-" * 20)
    for i, (params, score) in enumerate(zip(results['hyperparameters'], results['scores']), 1):
        print(f"{score:<10.6f}")
        
    print("=" * 30)

    print(f"Best Score: {results['best_score']:.6f}")
    print("=" * 30)
    print(f"Best Hyperparameters:")
    print(f"  - l2_penalty: {results['best_hyperparameters']['l2_penalty']:.4f}")
    print(f"  - alpha: {results['best_hyperparameters']['alpha']:.6f}")
    print(f"  - max_iter: {results['best_hyperparameters']['max_iter']}")


Performing Randomized Search CV...

Randomized Search Results:
Score     
--------------------
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
0.454545  
Best Score: 0.454545
Best Hyperparameters:
  - l2_penalty: 6.0000
  - alpha: 0.000109
  - max_iter: 1688


Exercise 12: Dropout layer
A dropout layer in NNs is a regularization technique where a random set of neurons
is temporarily ignored (dropped out) during training, helping prevent overfitting by
promoting robustness and generalization in the model.


• 12.1) Add a new layer named Dropout to the layers module; Take into consideration the
following structure.


• 12.2) Test the layer with a random input and check if the output shows the
desired behaviour

In [34]:
# Example usage
if __name__ == "__main__":
    # Create a dropout layer with 30% dropout probability
    dropout = Dropout(probability=0.3)
    
    # Simulate input data (batch_size=4, features=5)
    input_data = np.random.randn(4, 5)
    print("Input data:")
    print(input_data)
    print(f"Input shape: {input_data.shape}")
    print()
    
    # Set input shape
    dropout.set_input_shape((5,))
    
    # Forward propagation during training
    print("=" * 60)
    print("Forward propagation (training=True):")
    print("=" * 60)
    output_train = dropout.forward_propagation(input_data, training=True)
    print("Output (some neurons dropped and scaled):")
    print(output_train)
    print(f"\nMask applied (1 = keep, 0 = drop):")
    print(dropout.mask)
    print(f"\nScaling factor: {1 / (1 - dropout.probability):.4f}")
    print()
    
    # Forward propagation during inference
    print("=" * 60)
    print("Forward propagation (training=False):")
    print("=" * 60)
    output_inference = dropout.forward_propagation(input_data, training=False)
    print("Output (all neurons active, no scaling):")
    print(output_inference)
    print()
    
    # Backward propagation
    print("=" * 60)
    print("Backward propagation:")
    print("=" * 60)
    # First do forward pass in training mode to create mask
    _ = dropout.forward_propagation(input_data, training=True)
    output_error = np.ones((4, 5))
    print(f"Output error (all ones):")
    print(output_error)
    input_error = dropout.backward_propagation(output_error)
    print(f"\nInput error (output_error * mask):")
    print(input_error)
    print()
    
    # Check properties
    print("=" * 60)
    print("Layer Properties:")
    print("=" * 60)
    print(f"Number of trainable parameters: {dropout.parameters()}")
    print(f"Output shape: {dropout.output_shape()}")
    print(f"Input shape: {dropout.input_shape()}")

Input data:
[[-0.57470921 -0.42149822  0.33982096 -0.00738015  0.76729684]
 [-1.14979258 -0.77533611  0.77314086 -0.80182784  1.38401572]
 [ 1.40520531  1.39232575 -0.88064082  0.07689495 -0.49343248]
 [ 0.92316261  1.70660495  0.87358942  0.00914435 -0.3655393 ]]
Input shape: (4, 5)

Forward propagation (training=True):
Output (some neurons dropped and scaled):
[[-0.82101315 -0.60214031  0.48545852 -0.01054307  1.09613834]
 [-0.         -1.10762301  1.10448694 -1.14546835  0.        ]
 [ 0.          1.98903679 -1.25805831  0.         -0.70490355]
 [ 1.31880373  2.43800708  1.24798488  0.         -0.        ]]

Mask applied (1 = keep, 0 = drop):
[[1 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [1 1 1 0 0]]

Scaling factor: 1.4286

Forward propagation (training=False):
Output (all neurons active, no scaling):
[[-0.57470921 -0.42149822  0.33982096 -0.00738015  0.76729684]
 [-1.14979258 -0.77533611  0.77314086 -0.80182784  1.38401572]
 [ 1.40520531  1.39232575 -0.88064082  0.07689495 -0.49343248]


### Exercise 13: TanhActivation and SoftmaxActivation classes
- The tanh activation layer in NNs applies the hyperbolic tangent function to the output of
neurons, squashing the values to the range of -1 to 1.
- The softmax activation layer in NNs transforms the raw output scores into a probability
distribution (that sums to 1), making it suitable for multi-class classification problems.
• 13.1) Add a new activation class named TanhActivation to the "activation" module.


In [35]:
# Example usage and testing
if __name__ == "__main__":
    print("=" * 70)
    print("Testing TanhActivation")
    print("=" * 70)
    
    # Create TanhActivation layer
    tanh = TanhActivation()
    tanh.set_input_shape((3,))
    
    # Test input
    input_data = np.array([[-2.0, 0.0, 2.0],
                           [-1.0, 0.5, 1.0]])
    print(f"Input:\n{input_data}\n")
    
    # Forward propagation
    output = tanh.forward_propagation(input_data, training=True)
    print(f"Tanh Output (range [-1, 1]):\n{output}\n")
    
    # Check range
    print(f"Min value: {np.min(output):.4f}")
    print(f"Max value: {np.max(output):.4f}\n")
    
    # Backward propagation
    output_error = np.ones_like(output)
    input_error = tanh.backward_propagation(output_error)
    print(f"Gradient (derivative):\n{input_error}\n")
    
    # Properties
    print(f"Output shape: {tanh.output_shape()}")
    print(f"Parameters: {tanh.parameters()}")
    
    

Testing TanhActivation
Input:
[[-2.   0.   2. ]
 [-1.   0.5  1. ]]

Tanh Output (range [-1, 1]):
[[-0.96402758  0.          0.96402758]
 [-0.76159416  0.46211716  0.76159416]]

Min value: -0.9640
Max value: 0.9640

Gradient (derivative):
[[0.07065082 1.         0.07065082]
 [0.41997434 0.78644773 0.41997434]]

Output shape: (3,)
Parameters: 0


13.2) Add a new activation class named SoftmaxActivation to the "activation" module.


In [36]:
print("\n" + "=" * 70)
print("Testing SoftmaxActivation")
print("=" * 70)

# Create SoftmaxActivation layer
softmax = SoftmaxActivation()
softmax.set_input_shape((4,))

# Test input (logits for 4 classes)
logits = np.array([[2.0, 1.0, 0.1, 0.5],
                    [1.0, 3.0, 2.0, 0.5],
                    [0.5, 0.5, 0.5, 0.5]])
print(f"Input (logits):\n{logits}\n")

# Forward propagation
probabilities = softmax.forward_propagation(logits, training=True)
print(f"Softmax Output (probabilities):\n{probabilities}\n")

# Check properties of probability distribution
print("Probability distribution properties:")
print(f"- All values in [0, 1]: {np.all((probabilities >= 0) & (probabilities <= 1))}")
print(f"- Sum per sample: {np.sum(probabilities, axis=1)}")
print(f"- Predicted classes (argmax): {np.argmax(probabilities, axis=1)}\n")

# Backward propagation
output_error = np.ones_like(probabilities)
input_error = softmax.backward_propagation(output_error)
print(f"Gradient (derivative):\n{input_error}\n")

# Properties
print(f"Output shape: {softmax.output_shape()}")
print(f"Parameters: {softmax.parameters()}")

print("\n" + "=" * 70)
print("Comparison: Tanh vs Sigmoid vs ReLU vs Softmax")
print("=" * 70)

test_input = np.array([[-3, -1, 0, 1, 3]])



sigmoid = SigmoidActivation()
sigmoid.set_input_shape((5,))

relu = ReLUActivation()
relu.set_input_shape((5,))

tanh_test = TanhActivation()
tanh_test.set_input_shape((5,))

print(f"Input: {test_input}")
print(f"Sigmoid (0 to 1): {sigmoid.forward_propagation(test_input, True)}")
print(f"Tanh (-1 to 1): {tanh_test.forward_propagation(test_input, True)}")
print(f"ReLU (0 to ∞): {relu.forward_propagation(test_input, True)}")

# For softmax, normalize to show probability distribution
softmax_test = SoftmaxActivation()
softmax_test.set_input_shape((5,))
print(f"Softmax (prob): {softmax_test.forward_propagation(test_input, True)}")
print(f"Softmax sum: {np.sum(softmax_test.forward_propagation(test_input, True))}")


Testing SoftmaxActivation
Input (logits):
[[2.  1.  0.1 0.5]
 [1.  3.  2.  0.5]
 [0.5 0.5 0.5 0.5]]

Softmax Output (probabilities):
[[0.57452172 0.21135473 0.08593042 0.12819312]
 [0.08536889 0.63079554 0.23205671 0.05177885]
 [0.25       0.25       0.25       0.25      ]]

Probability distribution properties:
- All values in [0, 1]: True
- Sum per sample: [1. 1. 1.]
- Predicted classes (argmax): [0 1 0]

Gradient (derivative):
[[0.24444651 0.16668391 0.07854638 0.11175965]
 [0.07808105 0.23289253 0.17820639 0.0490978 ]
 [0.1875     0.1875     0.1875     0.1875    ]]

Output shape: (4,)
Parameters: 0

Comparison: Tanh vs Sigmoid vs ReLU vs Softmax
Input: [[-3 -1  0  1  3]]
Sigmoid (0 to 1): [[0.04742587 0.26894142 0.5        0.73105858 0.95257413]]
Tanh (-1 to 1): [[-0.99505475 -0.76159416  0.          0.76159416  0.99505475]]
ReLU (0 to ∞): [[0 0 0 1 3]]
Softmax (prob): [[0.00205549 0.01518815 0.04128566 0.11222606 0.82924464]]
Softmax sum: 1.0


### Exercise 14: CategoricalCrossEntropy Class
Add a new loss function named CategoricalCrossEntropy to the
losses module.


In [37]:
# Example usage and testing
if __name__ == "__main__":
    print("=" * 70)
    print("Testing CategoricalCrossEntropy Loss Function")
    print("=" * 70)
    
    # Create loss function
    loss_fn = CategoricalCrossEntropy()
    
    # Example 1: Perfect prediction
    print("\nExample 1: Perfect Prediction")
    print("-" * 70)
    y_true = np.array([[1, 0, 0],   # Class 0
                       [0, 1, 0],   # Class 1
                       [0, 0, 1]])  # Class 2
    
    y_pred = np.array([[0.99, 0.005, 0.005],  # Predicts class 0
                       [0.005, 0.99, 0.005],  # Predicts class 1
                       [0.005, 0.005, 0.99]]) # Predicts class 2
    
    loss = loss_fn.loss(y_true, y_pred)
    derivative = loss_fn.derivative(y_true, y_pred)
    
    print(f"True labels (one-hot):\n{y_true}")
    print(f"\nPredicted probabilities:\n{y_pred}")
    print(f"\nLoss: {loss:.6f} (close to 0 = good)")
    print(f"\nDerivative shape: {derivative.shape}")
    print(f"Derivative:\n{derivative}")
    
    # Example 2: Poor prediction
    print("\n" + "=" * 70)
    print("Example 2: Poor Prediction")
    print("-" * 70)
    y_true = np.array([[1, 0, 0],   # True class 0
                       [0, 1, 0],   # True class 1
                       [0, 0, 1]])  # True class 2
    
    y_pred = np.array([[0.1, 0.5, 0.4],   # Predicts class 1 (wrong!)
                       [0.4, 0.1, 0.5],   # Predicts class 2 (wrong!)
                       [0.5, 0.4, 0.1]])  # Predicts class 0 (wrong!)
    
    loss = loss_fn.loss(y_true, y_pred)
    derivative = loss_fn.derivative(y_true, y_pred)
    
    print(f"True labels (one-hot):\n{y_true}")
    print(f"\nPredicted probabilities:\n{y_pred}")
    print(f"\nLoss: {loss:.6f} (high = bad)")
    print(f"\nDerivative:\n{derivative}")
    
    # Example 3: Random prediction (uniform distribution)
    print("\n" + "=" * 70)
    print("Example 3: Random Prediction (Uniform Distribution)")
    print("-" * 70)
    y_true = np.array([[1, 0, 0, 0],
                       [0, 1, 0, 0]])
    
    y_pred = np.array([[0.25, 0.25, 0.25, 0.25],  # Random guess
                       [0.25, 0.25, 0.25, 0.25]]) # Random guess
    
    loss = loss_fn.loss(y_true, y_pred)
    
    print(f"True labels (one-hot):\n{y_true}")
    print(f"\nPredicted probabilities (uniform):\n{y_pred}")
    print(f"\nLoss: {loss:.6f}")
    print(f"Expected loss for random guess with 4 classes: -log(0.25) = {-np.log(0.25):.6f}")
    
    # Example 4: Comparison with BinaryCrossEntropy
    print("\n" + "=" * 70)
    print("Example 4: Binary Case - Comparison with BinaryCrossEntropy")
    print("-" * 70)
    
    from si.neural_networks.losses import BinaryCrossEntropy
    
    # Binary classification as categorical (2 classes)
    y_true_cat = np.array([[1, 0],
                           [0, 1],
                           [1, 0]])
    
    y_pred_cat = np.array([[0.9, 0.1],
                           [0.2, 0.8],
                           [0.7, 0.3]])
    
    # Binary classification format
    y_true_bin = np.array([1, 1, 1])
    y_pred_bin = np.array([0.9, 0.8, 0.7])
    
    cat_loss = CategoricalCrossEntropy()
    bin_loss = BinaryCrossEntropy()
    
    loss_cat = cat_loss.loss(y_true_cat, y_pred_cat)
    loss_bin = bin_loss.loss(y_true_bin, y_pred_bin)
    
    print(f"Categorical loss (2 classes): {loss_cat:.6f}")
    print(f"Binary loss: {loss_bin:.6f}")
    print("\nNote: They should be similar but not identical due to formulation differences")
    
    # Example 5: Demonstrating numerical stability with clipping
    print("\n" + "=" * 70)
    print("Example 5: Numerical Stability (Clipping)")
    print("-" * 70)
    
    y_true = np.array([[1, 0, 0]])
    
    # Extreme predictions (would cause log(0) without clipping)
    y_pred_extreme = np.array([[0.0, 0.5, 0.5]])
    
    print(f"True labels: {y_true}")
    print(f"Extreme prediction (0.0 for true class): {y_pred_extreme}")
    
    try:
        loss = loss_fn.loss(y_true, y_pred_extreme)
        print(f"Loss (with clipping): {loss:.6f}")
        print("✓ Clipping prevented log(0) error!")
    except:
        print("✗ Error occurred (this shouldn't happen with proper clipping)")
    
    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)
    print("• Lower loss = better predictions")
    print("• Perfect prediction → loss ≈ 0")
    print("• Random guess → loss ≈ -log(1/n_classes)")
    print("• Used with softmax activation for multi-class classification")
    print("• np.clip prevents numerical instability (log(0) and division by 0)")
    print("=" * 70)

Testing CategoricalCrossEntropy Loss Function

Example 1: Perfect Prediction
----------------------------------------------------------------------
True labels (one-hot):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Predicted probabilities:
[[0.99  0.005 0.005]
 [0.005 0.99  0.005]
 [0.005 0.005 0.99 ]]

Loss: 0.030151 (close to 0 = good)

Derivative shape: (3, 3)
Derivative:
[[-1.01010101  0.          0.        ]
 [ 0.         -1.01010101  0.        ]
 [ 0.          0.         -1.01010101]]

Example 2: Poor Prediction
----------------------------------------------------------------------
True labels (one-hot):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Predicted probabilities:
[[0.1 0.5 0.4]
 [0.4 0.1 0.5]
 [0.5 0.4 0.1]]

Loss: 6.907755 (high = bad)

Derivative:
[[-10.   0.   0.]
 [  0. -10.   0.]
 [  0.   0. -10.]]

Example 3: Random Prediction (Uniform Distribution)
----------------------------------------------------------------------
True labels (one-hot):
[[1 0 0 0]
 [0 1 0 0]]

Predicted probabilities (unif

Exercise 16: Build, train and evaluate a neural network
• Build, train and evaluate a NN based on the following instructions:
- The training dataset has 32 features
- The task is binary classification
- Use the SGD optimizer
- Use the BinaryCrossEntropy loss
- Use the accuracy metric
- The model should contain:
• Dense layer 1
• ReLU activation layer 1
• Dense layer 2
• ReLU activation layer 2
• Output Dense layer
• Sigmoid activation layer
- The dense layers should reduce the number of units to half (except the last one)
- Train the NN for 100 epochs, with batch size of 16 with a learning rate of 0.01.
- Test the model with k fold cross validation (hint: use the functions implemented in
class 8)

In [44]:
import numpy as np
import pandas as pd
from si.data.dataset import Dataset
from si.neural_networks.neural_network import NeuralNetwork
from si.neural_networks.layers import DenseLayer
from si.neural_networks.activation import ReLUActivation, SigmoidActivation
from si.neural_networks.optimizers import SGD
from si.neural_networks.losses import BinaryCrossEntropy
from si.model_selection.cross_validate import k_fold_cross_validation
from si.metrics.accuracy import accuracy


def build_neural_network(n_features: int = 32, learning_rate: float = 0.01) -> NeuralNetwork:
    """
    Build a neural network for binary classification.
    
    Architecture:
    - Input: 32 features
    - Dense layer 1: 16 units (half of input)
    - ReLU activation 1
    - Dense layer 2: 8 units (half of previous)
    - ReLU activation 2
    - Output Dense layer: 1 unit (binary classification)
    - Sigmoid activation (output probabilities)
    
    Parameters
    ----------
    n_features : int
        Number of input features (default: 32)
    learning_rate : float
        Learning rate for SGD optimizer (default: 0.01)
    
    Returns
    -------
    NeuralNetwork
        The configured neural network
    """
    # Initialize the neural network
    model = NeuralNetwork(
        epochs=100,
        batch_size=16,
        optimizer=SGD,
        learning_rate=learning_rate,
        loss=BinaryCrossEntropy,
        metric=accuracy,
        verbose=True
    )
    
    # Add layers to the network
    # Dense layer 1: Reduce to half (32 -> 16)
    model.add(DenseLayer(n_units=n_features // 2, input_shape=(n_features,)))
    model.add(ReLUActivation())
    
    # Dense layer 2: Reduce to half again (16 -> 8)
    model.add(DenseLayer(n_units=n_features // 4))
    model.add(ReLUActivation())
    
    # Output layer: Single unit for binary classification
    model.add(DenseLayer(n_units=1))
    model.add(SigmoidActivation())
    
    return model


def train_and_evaluate(dataset: Dataset, n_features: int = 32, 
                      learning_rate: float = 0.01, cv: int = 5) -> dict:
    """
    Train and evaluate the neural network using k-fold cross-validation.
    
    Parameters
    ----------
    dataset : Dataset
        The dataset to train and evaluate on
    n_features : int
        Number of input features
    learning_rate : float
        Learning rate for SGD optimizer
    cv : int
        Number of folds for cross-validation
    
    Returns
    -------
    dict
        Dictionary containing evaluation results
    """
    print("=" * 70)
    print("Neural Network Configuration")
    print("=" * 70)
    print(f"Input features: {n_features}")
    print(f"Architecture: {n_features} -> {n_features//2} -> {n_features//4} -> 1")
    print(f"Optimizer: SGD (learning_rate={learning_rate})")
    print(f"Loss: BinaryCrossEntropy")
    print(f"Metric: Accuracy")
    print(f"Epochs: 100")
    print(f"Batch size: 16")
    print(f"Cross-validation folds: {cv}")
    print("=" * 70)
    print()
    
    # Build the model
    model = build_neural_network(n_features=n_features, learning_rate=learning_rate)
    
    # Display model summary
    print("Model Architecture:")
    print("-" * 70)
    print(f"{'Layer':<5} {'Type':<25} {'Output Shape':<20} {'Parameters':<15}")
    print("-" * 70)
    total_params = 0
    for i, layer in enumerate(model.layers, 1):
        layer_params = layer.parameters()
        total_params += layer_params
        print(f"{i:<5} {layer.layer_name():<25} {str(layer.output_shape()):<20} {layer_params:<15}")
    print("-" * 70)
    print(f"Total parameters: {total_params:,}")
    print("=" * 70)
    print()
    
    # Perform k-fold cross-validation
    print("Starting K-Fold Cross-Validation...")
    print("=" * 70)
    
    scores = k_fold_cross_validation(
        model=model,
        dataset=dataset,
        scoring=accuracy,
        cv=cv,
        seed=42
    )
    
    # Calculate statistics
    results = {
        'scores': scores,
        'mean_score': np.mean(scores),
        'std_score': np.std(scores),
        'min_score': np.min(scores),
        'max_score': np.max(scores)
    }
    
    return results


def display_results(results: dict):
    """
    Display the cross-validation results.
    
    Parameters
    ----------
    results : dict
        Dictionary containing evaluation results
    """
    print("\n" + "=" * 70)
    print("Cross-Validation Results")
    print("=" * 70)
    print(f"Individual fold scores:")
    for i, score in enumerate(results['scores'], 1):
        print(f"  Fold {i}: {score:.4f} ({score*100:.2f}%)")
    print("-" * 70)
    print(f"Mean Accuracy: {results['mean_score']:.4f} ({results['mean_score']*100:.2f}%)")
    print(f"Std Deviation: {results['std_score']:.4f}")
    print(f"Min Accuracy:  {results['min_score']:.4f} ({results['min_score']*100:.2f}%)")
    print(f"Max Accuracy:  {results['max_score']:.4f} ({results['max_score']*100:.2f}%)")
    print("=" * 70)


# Main execution
if __name__ == "__main__":
    print("\n" + "=" * 70)
    print("Exercise 16: Neural Network Binary Classification")
    print("=" * 70)
    print()
    
    # Option 1: Load from CSV (adjust path as needed)
    try:
        print("Loading dataset from CSV...")
        df = pd.read_csv('../datasets/breast_bin/breast-bin.csv', header=None)
        X = df.iloc[:, :-1].to_numpy()
        y = df.iloc[:, -1].to_numpy()
        
        # Ensure y is reshaped for binary classification
        if len(y.shape) == 1:
            y = y.reshape(-1, 1)
        
        n_features = X.shape[1]
        dataset = Dataset(X, y)
        
        print(f"✓ Dataset loaded successfully!")
        print(f"  - Samples: {X.shape[0]}")
        print(f"  - Features: {n_features}")
        print(f"  - Target shape: {y.shape}")
        print(f"  - Target unique values: {np.unique(y)}")
        print()
        
    except FileNotFoundError:
        print("Dataset file not found. Creating synthetic dataset...")
        # Option 2: Create synthetic dataset with 32 features
        n_samples = 1000
        n_features = 32
        
        np.random.seed(42)
        X = np.random.randn(n_samples, n_features)
        # Binary classification based on sum of first 10 features
        y = (np.sum(X[:, :10], axis=1) > 0).astype(float).reshape(-1, 1)
        
        dataset = Dataset(X, y)
        
        print(f"✓ Synthetic dataset created!")
        print(f"  - Samples: {n_samples}")
        print(f"  - Features: {n_features}")
        print(f"  - Task: Binary classification")
        print(f"  - Class distribution: {np.unique(y, return_counts=True)}")
        print()
    
    # Train and evaluate the model with k-fold cross-validation
    results = train_and_evaluate(
        dataset=dataset,
        n_features=n_features,
        learning_rate=0.01,
        cv=5
    )
    
    # Display results
    display_results(results)
    
    print("\n" + "=" * 70)
    print("Training a final model on the full dataset...")
    print("=" * 70)
    print()
    
    # Train a final model on the full dataset
    final_model = build_neural_network(n_features=n_features, learning_rate=0.01)
    final_model.fit(dataset)
    
    # Make predictions
    predictions = final_model.predict(dataset)
    
    # Binarize predictions (threshold at 0.5)
    predictions_binary = (predictions >= 0.5).astype(float)
    
    # Calculate final accuracy
    final_accuracy = accuracy(dataset.y, predictions_binary)
    
    print(f"\nFinal model accuracy on full dataset: {final_accuracy:.4f} ({final_accuracy*100:.2f}%)")
    
    # Show some example predictions
    print("\nExample predictions (first 10 samples):")
    print("-" * 70)
    print(f"{'Sample':<10} {'True Label':<15} {'Predicted Prob':<20} {'Predicted Label':<20}")
    print("-" * 70)
    for i in range(min(10, len(predictions))):
        print(f"{i+1:<10} {dataset.y[i][0]:<15.0f} {predictions[i][0]:<20.4f} {predictions_binary[i][0]:<20.0f}")
    print("-" * 70)
    
    print("\n" + "=" * 70)
    print("Exercise 16 Complete!")
    print("=" * 70)
    
    # Summary
    print("\nSummary:")
    print(f"✓ Built neural network with architecture: {n_features} -> {n_features//2} -> {n_features//4} -> 1")
    print(f"✓ Layers: DenseLayer -> ReLU -> DenseLayer -> ReLU -> DenseLayer -> Sigmoid")
    print(f"✓ Used SGD optimizer with learning rate 0.01")
    print(f"✓ Used BinaryCrossEntropy loss")
    print(f"✓ Used Accuracy metric")
    print(f"✓ Trained for 100 epochs with batch size 16")
    print(f"✓ Evaluated with {len(results['scores'])}-fold cross-validation")
    print(f"✓ Mean CV Accuracy: {results['mean_score']:.4f} ± {results['std_score']:.4f}")
    print(f"✓ Final model accuracy: {final_accuracy:.4f}")
    print("=" * 70)


Exercise 16: Neural Network Binary Classification

Loading dataset from CSV...
✓ Dataset loaded successfully!
  - Samples: 699
  - Features: 9
  - Target shape: (699, 1)
  - Target unique values: [0. 1.]

Neural Network Configuration
Input features: 9
Architecture: 9 -> 4 -> 2 -> 1
Optimizer: SGD (learning_rate=0.01)
Loss: BinaryCrossEntropy
Metric: Accuracy
Epochs: 100
Batch size: 16
Cross-validation folds: 5

Model Architecture:
----------------------------------------------------------------------
Layer Type                      Output Shape         Parameters     
----------------------------------------------------------------------
1     DenseLayer                (4,)                 40             
2     ReLUActivation            (4,)                 0              
3     DenseLayer                (2,)                 10             
4     ReLUActivation            (2,)                 0              
5     DenseLayer                (1,)                 3              
6     Si

In [47]:




# Build neural network
model = NeuralNetwork(
    epochs=100,
    batch_size=16,
    optimizer=SGD,
    learning_rate=0.01,
    loss=BinaryCrossEntropy,
    metric=accuracy,
    verbose=True
)

# Add layers: Dense -> ReLU -> Dense -> ReLU -> Dense -> Sigmoid
model.add(DenseLayer(n_units=n_features // 2, input_shape=(n_features,)))  # 32 -> 16
model.add(ReLUActivation())
model.add(DenseLayer(n_units=n_features // 4))  # 16 -> 8
model.add(ReLUActivation())
model.add(DenseLayer(n_units=1))  # Output: 1
model.add(SigmoidActivation())

# Test with k-fold cross-validation
scores = k_fold_cross_validation(
    model=model,
    dataset=bb_dataset,
    scoring=accuracy,
    cv=5,
    seed=42
)

# Display results
print("\n" + "=" * 50)
print("K-Fold Cross-Validation Results")
print("=" * 50)
for i, score in enumerate(scores, 1):
    print(f"Fold {i}: {score:.4f}")
print("-" * 50)
print(f"Mean: {np.mean(scores):.4f}")
print(f"Std:  {np.std(scores):.4f}")
print("=" * 50)

Epoch 1/100 - loss: 372.8839 - accuracy: 0.6286
Epoch 2/100 - loss: 365.7641 - accuracy: 0.6429
Epoch 3/100 - loss: 365.6557 - accuracy: 0.6429
Epoch 4/100 - loss: 365.5089 - accuracy: 0.6429
Epoch 5/100 - loss: 365.5038 - accuracy: 0.6429
Epoch 6/100 - loss: 365.6234 - accuracy: 0.6429
Epoch 7/100 - loss: 365.3917 - accuracy: 0.6429
Epoch 8/100 - loss: 365.4631 - accuracy: 0.6429
Epoch 9/100 - loss: 365.6351 - accuracy: 0.6429
Epoch 10/100 - loss: 365.4479 - accuracy: 0.6429
Epoch 11/100 - loss: 365.5364 - accuracy: 0.6429
Epoch 12/100 - loss: 365.8052 - accuracy: 0.6429
Epoch 13/100 - loss: 365.4264 - accuracy: 0.6429
Epoch 14/100 - loss: 365.5112 - accuracy: 0.6429
Epoch 15/100 - loss: 365.4501 - accuracy: 0.6429
Epoch 16/100 - loss: 365.7894 - accuracy: 0.6429
Epoch 17/100 - loss: 365.5078 - accuracy: 0.6429
Epoch 18/100 - loss: 365.5680 - accuracy: 0.6429
Epoch 19/100 - loss: 365.5629 - accuracy: 0.6429
Epoch 20/100 - loss: 365.3286 - accuracy: 0.6429
Epoch 21/100 - loss: 365.5075