# SIB - Exercícios de Avaliação 
### Karolina Lopes Barbosa - PG55129

In [ ]:
import pandas as pd 
import numpy as np
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.tanimoto_similarity import tanimoto_similarity
from si.decomposition.pca import PCA
from si.model_selection.split import stratified_train_test_split, train_test_split
from si.models.knn_regressor import KNNRegressor
from si.models.random_forest_classifier import RandomForestClassifier
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.model_selection.cross_validate import k_fold_cross_validation

### Exercise 1: NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [55]:
df = pd.read_csv('../datasets/iris/iris.csv')
#print(iris_dataset.to_string())
#iris_np = iris_dataset.to_numpy() 

print(df)
X = df.iloc[:, :-1].to_numpy() #pega todas as linhas menos a ultima coluna
y = df.iloc[:, -1].to_numpy() #pega todas as linhas e a ultima coluna 
features = df.columns[:-1].tolist() 
label = df.columns[-1]

iris_dataset = Dataset(X, y, features, label)


     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [56]:
iris_dataset.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [57]:
#array[linhas, colunas]
iris_np = df.to_numpy()

ind_var_2 = iris_np[:,[2]]
dim = ind_var_2.shape #or ndim

print(ind_var_2) 
print(dim) #print dimension

[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]
 [1.7]
 [1.4]
 [1.5]
 [1.4]
 [1.5]
 [1.5]
 [1.6]
 [1.4]
 [1.1]
 [1.2]
 [1.5]
 [1.3]
 [1.4]
 [1.7]
 [1.5]
 [1.7]
 [1.5]
 [1.0]
 [1.7]
 [1.9]
 [1.6]
 [1.6]
 [1.5]
 [1.4]
 [1.6]
 [1.6]
 [1.5]
 [1.5]
 [1.4]
 [1.5]
 [1.2]
 [1.3]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.6]
 [1.9]
 [1.4]
 [1.6]
 [1.4]
 [1.5]
 [1.4]
 [4.7]
 [4.5]
 [4.9]
 [4.0]
 [4.6]
 [4.5]
 [4.7]
 [3.3]
 [4.6]
 [3.9]
 [3.5]
 [4.2]
 [4.0]
 [4.7]
 [3.6]
 [4.4]
 [4.5]
 [4.1]
 [4.5]
 [3.9]
 [4.8]
 [4.0]
 [4.9]
 [4.7]
 [4.3]
 [4.4]
 [4.8]
 [5.0]
 [4.5]
 [3.5]
 [3.8]
 [3.7]
 [3.9]
 [5.1]
 [4.5]
 [4.5]
 [4.7]
 [4.4]
 [4.1]
 [4.0]
 [4.4]
 [4.6]
 [4.0]
 [3.3]
 [4.2]
 [4.2]
 [4.2]
 [4.3]
 [3.0]
 [4.1]
 [6.0]
 [5.1]
 [5.9]
 [5.6]
 [5.8]
 [6.6]
 [4.5]
 [6.3]
 [5.8]
 [6.1]
 [5.1]
 [5.3]
 [5.5]
 [5.0]
 [5.1]
 [5.3]
 [5.5]
 [6.7]
 [6.9]
 [5.0]
 [5.7]
 [4.9]
 [6.7]
 [4.9]
 [5.7]
 [6.0]
 [4.8]
 [4.9]
 [5.6]
 [5.8]
 [6.1]
 [6.4]
 [5.6]
 [5.1]
 [5.6]
 [6.1]
 [5.6]
 [5.5]
 [4.8]
 [5.4]
 [5.6]
 [5.1]
 [5.1]

1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [58]:
last_10 = iris_np[-10:,] 
#last_10 = iris_np[-10:,[3]]
#mean_last_10 = np.mean(last_10)

print(last_10)

[[6.7 3.1 5.6 2.4 'Iris-virginica']
 [6.9 3.1 5.1 2.3 'Iris-virginica']
 [5.8 2.7 5.1 1.9 'Iris-virginica']
 [6.8 3.2 5.9 2.3 'Iris-virginica']
 [6.7 3.3 5.7 2.5 'Iris-virginica']
 [6.7 3.0 5.2 2.3 'Iris-virginica']
 [6.3 2.5 5.0 1.9 'Iris-virginica']
 [6.5 3.0 5.2 2.0 'Iris-virginica']
 [6.2 3.4 5.4 2.3 'Iris-virginica']
 [5.9 3.0 5.1 1.8 'Iris-virginica']]


1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [59]:
values = iris_np[:,0:3] <= 6
count_values = np.sum(values)
print(count_values)



380


1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain?

In [60]:
no_setosa = iris_np[:,-1] != 'Iris-setosa'

iris_filtered = iris_np[no_setosa]
print(iris_filtered)

[[7.0 3.2 4.7 1.4 'Iris-versicolor']
 [6.4 3.2 4.5 1.5 'Iris-versicolor']
 [6.9 3.1 4.9 1.5 'Iris-versicolor']
 [5.5 2.3 4.0 1.3 'Iris-versicolor']
 [6.5 2.8 4.6 1.5 'Iris-versicolor']
 [5.7 2.8 4.5 1.3 'Iris-versicolor']
 [6.3 3.3 4.7 1.6 'Iris-versicolor']
 [4.9 2.4 3.3 1.0 'Iris-versicolor']
 [6.6 2.9 4.6 1.3 'Iris-versicolor']
 [5.2 2.7 3.9 1.4 'Iris-versicolor']
 [5.0 2.0 3.5 1.0 'Iris-versicolor']
 [5.9 3.0 4.2 1.5 'Iris-versicolor']
 [6.0 2.2 4.0 1.0 'Iris-versicolor']
 [6.1 2.9 4.7 1.4 'Iris-versicolor']
 [5.6 2.9 3.6 1.3 'Iris-versicolor']
 [6.7 3.1 4.4 1.4 'Iris-versicolor']
 [5.6 3.0 4.5 1.5 'Iris-versicolor']
 [5.8 2.7 4.1 1.0 'Iris-versicolor']
 [6.2 2.2 4.5 1.5 'Iris-versicolor']
 [5.6 2.5 3.9 1.1 'Iris-versicolor']
 [5.9 3.2 4.8 1.8 'Iris-versicolor']
 [6.1 2.8 4.0 1.3 'Iris-versicolor']
 [6.3 2.5 4.9 1.5 'Iris-versicolor']
 [6.1 2.8 4.7 1.2 'Iris-versicolor']
 [6.4 2.9 4.3 1.3 'Iris-versicolor']
 [6.6 3.0 4.4 1.4 'Iris-versicolor']
 [6.8 2.8 4.8 1.4 'Iris-versicolor']
 

### Exercise 2: NumPy array Indexing/Slicing

2.1) Add a method to the Dataset class that removes
all samples containing at least one null value (NaN).
Note that the resulting object should not contain null
values in any independent feature/variable. Also,
note that you should update the y vector by
removing entries associated with the samples to be
removed. You should use only NumPy functions.
Method name: dropna

In [61]:
df_w_nas = pd.read_csv('../datasets/iris/iris_missing_data.csv', sep=',')

#definir X (var ind - todas as colunas menos a ultima)
X_w_nas = df_w_nas.iloc[:, :-1].to_numpy()

#fazer novo dataset com nas
dataset_w_nas = Dataset(X_w_nas, y, features, label)

#tirar nas do dataset
dataset_dropna = dataset_w_nas.dropna()

2.2) Add a method to the Dataset class that
replaces all null values with another value or the
mean or median of the feature/variable. Note that
the resulting object should not contain null values
in any independent feature/variable. You should
use only NumPy functions.
Method name: fillna

In [62]:
dataset_w_nas.X
fill_nas = dataset_w_nas.fillna("median")
#fill_nas = dataset_w_nas.fillna("mean")
#fill_nas = dataset_w_nas.fillna(0)
fill_nas.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 1.3],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 3. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 1.3],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

 2.3) Add a method to the Dataset class that
removes a sample by its index. Note that you
should also update the y vector by removing the
entry associated with the sample to be removed.
You should use only NumPy functions.
Method name: remove_by_index

In [63]:
remove_index = iris_dataset.remove_by_index([1,3])
remove_index.shape()

(148, 4)

### Exercise 3: Implementing SelectPercentile

3.1) Add the SelectPercentile object to the
feature_selection sub-package. You should create a
module called "select_percentile.py" to implement
this object. 

3.2) Test the SelectPercentile class in a Jupyter
notebook using the "iris.csv" dataset
(classification).

In [64]:
selector = SelectPercentile(percentile=40)
selector = selector.fit(iris_dataset)
print("\nOriginal example - F-scores:", selector.F)
print("Selected features (40%):", selector.transform(iris_dataset).features)
print("Number of features:", len(selector.transform(iris_dataset).features))


Original example - F-scores: [ 113.91732389   48.74222679 1134.44343705  923.18929086]
Selected features (40%): [np.str_('petal_length'), np.str_('petal_width')]
Number of features: 2


### Exercise 4: Implementing Tanimoto Similarity

4.1) Implement the Tanimoto Similarity in file tanimoto_similarity.py (in the sub-package statistics) in file tanimoto_similarity.py (in the sub-package statistics)

In [65]:
x = iris_dataset.X[0]      # Primeira amostra: shape (4,)
y = iris_dataset.X         # Todas as amostras: shape (148, 4)
print(f"x = {x}")
print(f"y shape = {y.shape}")
print(f"Similarities = {tanimoto_similarity(x, y)}")

x = [5.1 3.5 1.4 0.2]
y shape = (148, 4)
Similarities = [1.         0.99302762 0.9995015  0.99136952 0.99282869 0.99924185
 0.9760158  0.99423782 0.99672668 0.99639175 0.99061914 0.97169811
 0.98307292 0.97451431 0.99308596 0.9997518  0.98787478 0.9973545
 0.99548157 0.99781712 0.98892405 0.99453552 0.99112351 0.99222395
 0.9974887  0.99951136 0.99950544 0.99231585 0.99234828 0.99640891
 0.99100968 0.98568282 0.99423782 0.99636929 0.99598394 0.99423782
 0.97890295 0.99950087 0.99924357 0.94755043 0.98365198 0.99479167
 0.99104407 0.99062918 0.99688399 0.99081081 0.9978678  0.99872123
 0.77031093 0.7940806  0.75418202 0.81428294 0.77555798 0.79562172
 0.77923278 0.87417067 0.78225182 0.83336663 0.83723002 0.81780031
 0.81666667 0.7785148  0.86856128 0.79634788 0.79463975 0.83231538
 0.76380572 0.8380117  0.76510598 0.8317624  0.74573114 0.78105056
 0.80786961 0.79634876 0.75862069 0.74268171 0.79154129 0.87431804
 0.84097737 0.85141461 0.84221427 0.73533509 0.79317697 0.79856934
 0.7723

### Exercise 5: Implement the PCA Class

5.1) Add the "PCA" class in the "pca.py" module on
the "decomposition" sub-package. Consider the
PCA class structure presented in the next slide.

5.2) Test the PCA class in a jupyter notebook using
the iris.csv dataset (classificação).

In [66]:
pca_iris = PCA(n_components=4)
iris_X_reduced = pca_iris.fit_transform(iris_dataset)
print("Mean:")
print(pca_iris.mean)

print("\nComponents (eigenvectors):")
print(pca_iris.components)

print("\nExplained variance (ratio):")
print(pca_iris.explained_variance)

print("\nReduced dataset:")
print(iris_X_reduced)

Mean:
[5.85810811 3.05405405 3.78986486 1.21216216]

Components (eigenvectors):
[[ 0.36054742 -0.65788934 -0.5791591   0.31900144]
 [-0.08443357 -0.72898775  0.59616064 -0.32563834]
 [ 0.8568705   0.17377001  0.0716297  -0.48004804]
 [ 0.35867741  0.07458196  0.55139497  0.74950092]]

Explained variance (ratio):
[0.92316712 0.05403909 0.01751521 0.00527858]

Reduced dataset:
[[-2.72183113e+00 -3.17113775e-01 -2.43657900e-02  1.57878848e-03]
 [-2.92640707e+00  1.47361283e-01  2.12866862e-02  1.96745157e-02]
 [-2.76632922e+00 -3.24223616e-01  9.31661840e-02 -6.28851893e-02]
 [-2.31864370e+00 -7.39028279e-01  1.72118641e-01 -2.70903394e-02]
 [-2.85779374e+00  9.21878641e-02  2.60737191e-01 -5.04080070e-02]
 [-2.66375546e+00 -1.61049065e-01 -1.89029752e-02 -4.57623261e-02]
 [-2.92355417e+00  5.80801409e-01  2.33491917e-02 -2.63392204e-02]
 [-2.71034787e+00  1.15977997e-01 -1.94974756e-01 -5.49210623e-02]
 [-2.54486656e+00 -6.42901124e-01 -7.17184208e-02 -1.58532495e-02]
 [-2.65017789e+00 -

### Exercise 6: Implementing stratified splitting

6.1) In the "split.py" module of the
"model_selection" subpackage add
the "stratified_train_test_split" function.

6.2) Test the "stratified_train_test_split" function
with the iris dataset.

In [67]:
train_strat, test_strat = stratified_train_test_split(iris_dataset, test_size=0.2, random_state=42)

print(f"Train set: {len(train_strat.y)} samples")
unique, counts = np.unique(train_strat.y, return_counts=True)
for label, count in zip(unique, counts):
    print(f"  Class {label}: {count} samples ({count/len(train_strat.y)*100:.1f}%)")

print(f"\nTest set: {len(test_strat.y)} samples")
unique, counts = np.unique(test_strat.y, return_counts=True)
for label, count in zip(unique, counts):
    print(f"  Class {label}: {count} samples ({count/len(test_strat.y)*100:.1f}%)")
print()

Train set: 119 samples
  Class Iris-setosa: 39 samples (32.8%)
  Class Iris-versicolor: 40 samples (33.6%)
  Class Iris-virginica: 40 samples (33.6%)

Test set: 29 samples
  Class Iris-setosa: 9 samples (31.0%)
  Class Iris-versicolor: 10 samples (34.5%)
  Class Iris-virginica: 10 samples (34.5%)



### Exercise 7: Implementing the KNNRegressor with RMSE

7.1) Add the RMSE metric to the "metrics" sub-package.
You must create a new module named "rmse.py".
Consider the structure of the rmse function as presented
in the following slide.

In [68]:
from si.metrics.rmse import rmse
#o objetivo dos testes é verificar como se comportaria a função qnd n tem erros, com pequenos e maiores erros.
if __name__ == '__main__':
    print("=" * 70)
    print("TEST 1: Perfect predictions")
    print("=" * 70)
    y_true1 = np.array([1, 2, 3, 4, 5])
    y_pred1 = np.array([1, 2, 3, 4, 5])
    print(f"y_true: {y_true1}")
    print(f"y_pred: {y_pred1}")
    print(f"RMSE: {rmse(y_true1, y_pred1):.6f}")
    print("Expected: 0.0 (perfect predictions)")
    print()
    
    print("=" * 70)
    print("TEST 2: Small errors")
    print("=" * 70)
    y_true2 = np.array([3, -0.5, 2, 7])
    y_pred2 = np.array([2.5, 0.0, 2, 8])
    print(f"y_true: {y_true2}")
    print(f"y_pred: {y_pred2}")
    print(f"RMSE: {rmse(y_true2, y_pred2):.6f}")
    print("Errors: [-0.5, 0.5, 0, 1]")
    print()
    
    print("=" * 70)
    print("TEST 3: Larger errors")
    print("=" * 70)
    y_true3 = np.array([10, 20, 30, 40, 50])
    y_pred3 = np.array([12, 18, 35, 38, 55])
    print(f"y_true: {y_true3}")
    print(f"y_pred: {y_pred3}")
    print(f"RMSE: {rmse(y_true3, y_pred3):.6f}")
    print("Errors: [2, -2, 5, -2, 5]")
    print()
    
    print("=" * 70)
    print("TEST 5: Comparison - small vs large errors")
    print("=" * 70)
    y_true5 = np.array([10, 10, 10, 10])
    
    # Case A: consistent small errors
    y_pred5a = np.array([11, 11, 11, 11])
    rmse_a = rmse(y_true5, y_pred5a)
    print(f"Case A - Consistent small errors (+1 each):")
    print(f"  y_pred: {y_pred5a}")
    print(f"  RMSE: {rmse_a:.6f}")
    
    # Case B: one large error
    y_pred5b = np.array([10, 10, 10, 14])
    rmse_b = rmse(y_true5, y_pred5b)
    print(f"\nCase B - One large error (+4 on last):")
    print(f"  y_pred: {y_pred5b}")
    print(f"  RMSE: {rmse_b:.6f}")
    
    print(f"\nNote: RMSE penalizes large errors more heavily!")
    print(f"Case A (4 errors of +1): RMSE = {rmse_a:.3f}")
    print(f"Case B (1 error of +4): RMSE = {rmse_b:.3f}")
    print()
    
    print("=" * 70)
    print("TEST 6: Real-world example - House price prediction")
    print("=" * 70)
    # Prices in thousands of dollars
    y_true6 = np.array([250, 300, 350, 400, 450])  # True prices
    y_pred6 = np.array([245, 310, 340, 395, 460])  # Predicted prices
    
    print(f"True prices (K$): {y_true6}")
    print(f"Predicted prices (K$): {y_pred6}")
    print(f"RMSE: ${rmse(y_true6, y_pred6):.2f}K")
    print(f"\nInterpretation: On average, predictions are off by ~${rmse(y_true6, y_pred6):.2f}K")

TEST 1: Perfect predictions
y_true: [1 2 3 4 5]
y_pred: [1 2 3 4 5]
RMSE: 0.000000
Expected: 0.0 (perfect predictions)

TEST 2: Small errors
y_true: [ 3.  -0.5  2.   7. ]
y_pred: [2.5 0.  2.  8. ]
RMSE: 0.612372
Errors: [-0.5, 0.5, 0, 1]

TEST 3: Larger errors
y_true: [10 20 30 40 50]
y_pred: [12 18 35 38 55]
RMSE: 3.521363
Errors: [2, -2, 5, -2, 5]

TEST 5: Comparison - small vs large errors
Case A - Consistent small errors (+1 each):
  y_pred: [11 11 11 11]
  RMSE: 1.000000

Case B - One large error (+4 on last):
  y_pred: [10 10 10 14]
  RMSE: 2.000000

Note: RMSE penalizes large errors more heavily!
Case A (4 errors of +1): RMSE = 1.000
Case B (1 error of +4): RMSE = 2.000

TEST 6: Real-world example - House price prediction
True prices (K$): [250 300 350 400 450]
Predicted prices (K$): [245 310 340 395 460]
RMSE: $8.37K

Interpretation: On average, predictions are off by ~$8.37K


7.2) Add the "KNNRegressor" class to the "models" subpackage. You should create a module named
"knn_regressor.py" to implement this class. Consider the
structure of the "KNNRegressor" as presented in the next
slides.

7.3) Test the "KNNRegressor" class using the "cpu.csv"
dataset (regression).

In [69]:
df = pd.read_csv('../datasets/cpu/cpu.csv')

X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()
features = df.columns[:-1].tolist()
label = df.columns[-1]

cpu_dataset = Dataset(X, y, features, label)


 # Split the dataset
train_dataset, test_dataset = train_test_split(cpu_dataset, test_size=0.2, random_state=42)
print(f"Training samples: {train_dataset.shape()[0]}")
print(f"Testing samples: {test_dataset.shape()[0]}")

# Find best k value for KNN regressor 
k_values = [1, 3, 5, 10, 20]

print("Testing different k values:")
print("-" * 70)
for k in k_values:
    knn = KNNRegressor(k=k)
    knn.fit(train_dataset)
    score = knn.score(test_dataset)
    print(f"k={k:2d} -> RMSE: {score:.2f}")



Training samples: 168
Testing samples: 41
Testing different k values:
----------------------------------------------------------------------
k= 1 -> RMSE: 100.57
k= 3 -> RMSE: 81.36
k= 5 -> RMSE: 104.97
k=10 -> RMSE: 132.54
k=20 -> RMSE: 156.32


### Exercise 8: Implementing RidgeRegression with Least Squares


In the "models" sub-package add the
"ridge_regression_least_squares.py" module which will contain
the RidgeRegressionLeastSquates class 

In [70]:
from si.data.dataset import Dataset
from si.model_selection.split import train_test_split
from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares

# criar dataset aleatório
dataset = Dataset.from_random(n_samples=200, n_features=5)

# dividir entre treino e teste
train, test = train_test_split(dataset, test_size=0.2)

# criar modelo
model = RidgeRegressionLeastSquares(l2_penalty=1.0, scale=True)

# treinar
model.fit(train)

# mostrar parâmetros aprendidos
print("Theta (coeficientes):")
print(model.theta)

print("\nTheta_zero (intercepto):")
print(model.theta_zero)

# prever no test set
predictions = model.predict(test)

print("\nPrimeiras 10 previsões:")
print(predictions[:10])

print("\nPrimeiros 10 valores reais:")
print(test.y[:10])

# calcular score
score = model.score(test)
print(f"\nMSE score no test set: {score:.4f}")

Theta (coeficientes):
[ 0.04299948 -0.02005872  0.02527278  0.00540694 -0.00930056]

Theta_zero (intercepto):
0.5125000000000001

Primeiras 10 previsões:
[0.50072814 0.52228111 0.44321972 0.45068486 0.50499773 0.55127592
 0.5173332  0.54721859 0.49944067 0.51111671]

Primeiros 10 valores reais:
[0 0 0 0 0 0 0 0 1 1]

MSE score no test set: 0.2516


### Exercise 9: Implementing the RandomForestClassifier class

9.1) In the "models" sub-package add the
"random_forest_classifier.py" module. Implement the
RandomForestClassifier class by taking into consideration the
structure of the class shown in the next slides.

9.2) Test the random forest class using the following protocol:  


1.Use the iris.csv dataset. 

2.Split the data into train and test sets. 

3.Create the RandomForestClassifier model. 

4.Train the model. What is the score of the model on the test set?

In [71]:
if __name__ == "__main__":

    train, test = train_test_split(iris_dataset, test_size=0.2, random_state=42)

    model = RandomForestClassifier(
        n_estimators=10,
        max_depth=4,
        min_sample_split=2,
        mode="gini",
        seed=42
    )

    model.fit(train)
    preds = model.predict(test)
    print("Accuracy:", model.score(test))

Accuracy: 0.8620689655172413


### Exercise 10: Implementing the StackingClassifier ensemble

10.1) In the "ensemble" sub-package add the "stacking_classifier.py" module. Implement
the StackingClassifier class by taking into consideration the structure of the class shown
in the next slides.

In [72]:
import numpy as np
from si.base.model import Model
from si.data.dataset import Dataset
from si.metrics.accuracy import accuracy


class StackingClassifier(Model):
    """
    Stacking Classifier ensemble model.
    
    The StackingClassifier uses an ensemble of base models to generate predictions.
    These predictions are then used as features to train a final model that makes
    the ultimate predictions.
    
    Parameters
    ----------
    models : list
        List of base models to use in the ensemble
    final_model : Model
        The model to make the final predictions based on base model outputs
        
    Attributes
    ----------
    models : list
        The fitted base models
    final_model : Model
        The fitted final model
    """
    
    def __init__(self, models: list, final_model: Model, **kwargs):
        """
        Initialize the StackingClassifier.
        
        Parameters
        ----------
        models : list
            Initial set of base models
        final_model : Model
            The model to make the final predictions
        """
        super().__init__(**kwargs)
        self.models = models
        self.final_model = final_model
        
    def _fit(self, dataset: Dataset) -> 'StackingClassifier':
        """
        Train the stacking classifier.
        
        Algorithm:
        1. Train the initial set of models
        2. Get predictions from the initial set of models
        3. Train the final model with the predictions of the initial set of models
        4. Return itself (self)
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to fit the model to
            
        Returns
        -------
        self : StackingClassifier
            The fitted model
        """
        # Step 1: Train the initial set of models
        for model in self.models:
            model.fit(dataset)
        
        # Step 2: Get predictions from the initial set of models
        base_predictions = np.column_stack([
            model.predict(dataset) for model in self.models
        ])
        
        # Step 3: Train the final model with the predictions of the initial set of models
        # Create a new dataset with base predictions as features and original labels
        stacked_dataset = Dataset(X=base_predictions, y=dataset.y)
        self.final_model.fit(stacked_dataset)
        
        # Step 4: Return itself
        return self
    
    def _predict(self, dataset: Dataset) -> np.ndarray:
        """
        Predict class labels using the stacking classifier.
        
        Algorithm:
        1. Get predictions from the initial set of models
        2. Get the final predictions using the final model and the 
           predictions of the initial set of models
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to predict the classes of
            
        Returns
        -------
        predictions : np.ndarray
            Predicted class labels
        """
        # Step 1: Get predictions from the initial set of models
        base_predictions = np.column_stack([
            model.predict(dataset) for model in self.models
        ])
        
        # Step 2: Get the final predictions using the final model
        # Create a new dataset with base predictions as features
        stacked_dataset = Dataset(X=base_predictions, y=dataset.y)
        final_predictions = self.final_model.predict(stacked_dataset)
        
        return final_predictions
    
    def _score(self, dataset: Dataset, predictions: np.ndarray) -> float:
        """
        Compute the accuracy score of the stacking classifier.
        
        Algorithm:
        1. Compute the accuracy between predicted and real values
        
        Parameters
        ----------
        dataset : Dataset
            The dataset to evaluate the model on
        predictions : np.ndarray
            An array with the predictions
            
        Returns
        -------
        accuracy : float
            The accuracy score (proportion of correct predictions)
        """
        # Compute the accuracy between predicted and real values
        return accuracy(dataset.y, predictions)


10.2) Test the StackingClassifier model using the following protocol:


1.Use the breast-bin.csv dataset


2.Split the data into train and test sets


3.Create a KNNClassifier model


4.Create a LogisticRegression model


5.Create a DecisionTree model


6.Create a second KNNClassifier model (final model)


7.Create a StackingClassifier model using the previous classifiers. The second KNNClassifier model must be used as the final model.


8.Train the StackingClassifier model. What is the score of the model on the test set?

In [84]:
df = pd.read_csv('../datasets/breast_bin/breast-bin.csv', header= None)
X = df.iloc[:, :-1].to_numpy()  # All columns except last
y = df.iloc[:, -1].to_numpy()    # Last column
features = [f'feature_{i}' for i in range(X.shape[1])]
label = 'target'


if __name__ == "__main__":
    
    bb_dataset = Dataset(X, y, features, label)

    # Initialize base models
    base_models = [
        KNNClassifier(k=3),
        LogisticRegression(),
        DecisionTreeClassifier()
    ]
    
    # Initialize final model
    final_model = KNNClassifier(k=3)
    
    # Create and train stacking classifier
    stacking = StackingClassifier(models=base_models, final_model=final_model)
    train_dataset, test_dataset = train_test_split(bb_dataset, test_size=0.2, random_state=42)
    stacking.fit(train_dataset)
    
    # Make predictions
    predictions = stacking.predict(test_dataset)
    print(f"Predictions: {predictions}")
    
    # Compute accuracy
    accuracy_score = stacking.score(test_dataset)
    print(f"Accuracy: {accuracy_score}")

Predictions: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1.]
Accuracy: 0.9280575539568345


### Exercise 11: Implementing the randomized_search_cv function.

11.1) In the "model_selection" sub-package add the "randomized_search.py"
module. Implement the randomized_search_cv function by considering the
structure presented in the next slides.

In [ ]:
from typing import Dict, Callable, List, Any
import numpy as np
import itertools
from si.base.model import Model
from si.data.dataset import Dataset



def randomized_search_cv(model: Model,
                         dataset: Dataset,
                         hyperparameter_grid: Dict[str, List[Any]],
                         scoring: Callable = None,
                         cv: int = 3,
                         n_iter: int = 10,
                         seed: int = None) -> Dict[str, Any]:
    """
    Perform randomized search cross-validation on the given model and dataset.
    
    This function randomly samples n_iter combinations from the hyperparameter grid,
    evaluates each combination using k-fold cross-validation, and returns the best
    performing hyperparameters.

    Parameters
    ----------
    model : Model
        The model to validate
    dataset : Dataset
        The validation dataset
    hyperparameter_grid : Dict[str, List[Any]]
        Dictionary with the hyperparameter names as keys and lists of possible
        values to search as values
    scoring : Callable, optional
        Score function to use. If None, the model's score method will be used
    cv : int, default=3
        Number of cross-validation folds
    n_iter : int, default=10
        Number of random hyperparameter combinations to test
    seed : int, optional
        Random seed for reproducibility

    Returns
    -------
    results : Dict[str, Any]
        Dictionary with the following keys:
        - 'hyperparameters': list of all hyperparameter combinations tested
        - 'scores': list of mean scores obtained for each combination
        - 'best_hyperparameters': best combination of hyperparameters
        - 'best_score': best mean score achieved

    Raises
    ------
    ValueError
        If any hyperparameter in the grid does not exist in the model

    """

    # Step 1: Check if the provided hyperparameters are valid
    for hyperparameter in hyperparameter_grid.keys():
        if not hasattr(model, hyperparameter):
            raise ValueError(f"Model {model.__class__.__name__} does not have "
                           f"hyperparameter '{hyperparameter}'")
    
    # Step 2: Get n_iter hyperparameter combinations
    # Generate all possible combinations
    hyperparameter_names = list(hyperparameter_grid.keys())
    hyperparameter_values = list(hyperparameter_grid.values())
    all_combinations = list(itertools.product(*hyperparameter_values))
    
    # Randomly sample n_iter combinations (or all if n_iter > total combinations)
    if seed is not None:
        np.random.seed(seed)
    
    n_combinations = min(n_iter, len(all_combinations))
    random_indices = np.random.choice(len(all_combinations), 
                                     size=n_combinations, 
                                     replace=False)
    selected_combinations = [all_combinations[i] for i in random_indices]
    
    # Initialize results storage
    all_hyperparameters = []
    all_scores = []
    best_score = -np.inf
    best_hyperparameters = None
    
    # Step 3-6: Iterate through all selected hyperparameter combinations
    for combination in selected_combinations:
        # Step 3: Set the model hyperparameters with the current combination
        current_hyperparameters = {}
        for hyperparameter_name, hyperparameter_value in zip(hyperparameter_names, combination):
            setattr(model, hyperparameter_name, hyperparameter_value)
            current_hyperparameters[hyperparameter_name] = hyperparameter_value
        
        # Step 4: Cross validate the model using k_fold_cross_validation
        fold_scores = k_fold_cross_validation(model, dataset, scoring=scoring, cv=cv, seed=seed)
        
        # Step 5: Save the mean of the scores and respective hyperparameters
        mean_score = np.mean(fold_scores)
        all_hyperparameters.append(current_hyperparameters.copy())
        all_scores.append(mean_score)
        
        # Step 7: Update best score and hyperparameters if current is better
        if mean_score > best_score:
            best_score = mean_score
            best_hyperparameters = current_hyperparameters.copy()
    
    # Step 8: Return results dictionary
    results = {
        'hyperparameters': all_hyperparameters,
        'scores': all_scores,
        'best_hyperparameters': best_hyperparameters,
        'best_score': best_score
    }
    
    return results



11.2) Test the randomized_search_cv function using the following protocol:


1. Use the breast-bin.csv dataset


2. Create a LogisticRegression model


3. Perform a randomized search with the following hyperparameter distributions:


• l2_penalty: distribution between 1 and 10 with 10 equal intervals (e.g., np.linspace(1, 10, 10))

• alpha: distribution between 0.001 and 0.0001 with 100 equal intervals (e.g., np.linspace(0.001, 0.0001, 100))

• max_iter: distribution between 1000 and 2000 with 200 equal intervals (e.g., np.linspace(1000, 2000, 200))


4. Use n_iter=10 and cv=3 folds for the cross validation.


5. Which scores do you obtain? What are the best score and best hyperparameters?

In [103]:

if __name__ == "__main__":
    
    # Create model
    model = LogisticRegression()
    
    # Define hyperparameter grid with distributions for LogisticRegression
    hyperparameter_grid = {
        'l2_penalty': np.linspace(1, 10, 10).tolist(),
        'alpha': np.linspace(0.001, 0.0001, 100).tolist(),
        'max_iter': np.linspace(1000, 2000, 200, dtype=int).tolist()
    }
    
    # Perform randomized search
    print("Performing Randomized Search CV...")
    results = randomized_search_cv(
        model=model,
        dataset=dataset,
        hyperparameter_grid=hyperparameter_grid,
        cv=3,
        n_iter=10,  # Test 10 random combinations out of 200,000 possible
        seed=42
    )
    
    # Display results
    print("\nRandomized Search Results:")
    print("=" * 20)

    print(f"{'Score':<10}")

    print("-" * 20)
    for i, (params, score) in enumerate(zip(results['hyperparameters'], results['scores']), 1):
        print(f"{score:<10.6f}")
        
    print("=" * 30)

    print(f"Best Score: {results['best_score']:.6f}")
    print("=" * 30)
    print(f"Best Hyperparameters:")
    print(f"  - l2_penalty: {results['best_hyperparameters']['l2_penalty']:.4f}")
    print(f"  - alpha: {results['best_hyperparameters']['alpha']:.6f}")
    print(f"  - max_iter: {results['best_hyperparameters']['max_iter']}")


Performing Randomized Search CV...

Randomized Search Results:
Score     
--------------------
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
0.967096  
Best Score: 0.967096
Best Hyperparameters:
  - l2_penalty: 6.0000
  - alpha: 0.000109
  - max_iter: 1688
